services:
  monitoring:
    image: monitoring-app
    container_name: monitoring
    restart: always
    environment:
      DB_URL: postgres://vpnadmin:secret@CENTRAL_VM_IP:5432/vpndb
    ports:
      - "8080:8080"